dataset:
  dataset_name: "StarLightCurves"
  in_channels: 1
  data_scaling: True
  batch_sizes:
    stage1: 128
    stage2: 256
  num_workers: 8

exp_params:
  LR: 0.001 #0.01
  weight_decay: 0.001 #0.00001
  reptest_per: 10

trainer_params:
  gpus:
    - 0
  max_epochs:
    stage1: 10 #2000
    stage2: 100 #1000 #1000 #10000

encoder:
  dim: 64
  dropout_rate: 0.0
  n_resnet_blocks: 4
  downsampled_width: 8

decoder:
  dim: 64
  dropout_rate: 0.0
  n_resnet_blocks: 4

VQVAE:
  n_fft: 8
  codebook:
    size: 32
    dim: 64
  decay: 0.8
  commitment_weight: 1
  emb_dropout: 0.
  perceptual_loss_weight: 0

  # Hyperparameters when VQVAE are processing
  # a original and augmented view of the same data.
  recon_alternate_view_scale: 0.1
  recon_original_view_scale: 0.9 #prioritize original view

MaskGIT:
  choice_temperature: 4 # for masking
  stochastic_sampling: 1 # from (Lee et al., 2022)
  T: 10
  prior_model:
    hidden_dim: 256
    n_layers: 4
    heads: 2
    ff_mult: 1
    use_rmsnorm: True
    p_unconditional: 0.2

MAGE:
  choice_temperature: 4 # for masking
  stochastic_sampling: 1 # from (Lee et al., 2022)
  T: 10
  prior_model:
    hidden_dim: 256
    encoder_layers: 3 #3
    decoder_layers: 2
    heads: 2
    ff_mult: 1
    use_rmsnorm: True
    p_unconditional: 0.2

  mask_ratio:
    min: 0.5
    max: 1.0
    mu: 0.55
    std: 0.25

class_guidance:
  guidance_scale: 1.

SSL:
  stage1_method: "" #"vibcreg" # "barlowtwins", "vicreg", "vibcreg" or empty
  stage1_weight: 0.01
  stage2_method: "vibcreg" #"barlowtwins" # "barlowtwins", "vicreg", "vibcreg" or empty
  stage2_weight: 1.0

  # Hyperparameters for SSL methods.
  # These are the default values from the paper on CV-methods on Time series. Ref: Lee et al.
  barlowtwins:
    proj_hid: 4096 #projector hidden layer size
    proj_out: 4096 #projector output layer size
    lambda: 0.005

  vicreg:
    proj_hid: 4096 #projector hidden layer size
    proj_out: 4096 #projector output layer size
    lambda: 25 # sim_loss
    mu: 25 # var_loss
    nu: 1 # cov_loss

  vibcreg:
    proj_hid: 4096 #projector hidden layer size
    proj_out: 4096 #projector output layer size
    lambda: 25 # sim_loss
    mu: 25 # var_loss
    nu: 100 # cov_loss

augmentations:
  use_all_methods: True

  time_augs:
    #- "noise"
    #- "amplitude_resize"
    - "slope"
    #- 'flip'
    - "noise_window"
  timefreq_augs:
    #- "random_masks"
    #- "block"
    #- "band"
    - "phase"
    #- 'rotation'
    - "gaussian"
    #- "shear"
    - "scale"

  aug_params:
    n_fft: 32
    #Time
    noise_std: 0.01
    noise_window_scale: 0.4
    AmpR_rate: 0.1
    slope_rate: 0.005
    #TimeFreq
    #Block aug:
    block_size_scale: 0.05
    block_density: 0.01
    #Band aug:
    num_bands_to_remove: 3
    band_scale_factor: 0.1
    #Gaussian aug:
    gaus_mean: 0
    gaus_std: 0.01
    #rotation aug:
    rotation_max_angle: 0.1
    #scale aug:
    min_scale: 0.9
    max_scale: 1.1
    #Random point-masks aug:
    random_mask_density: 0.01
    #Shear aug:
    max_shear_x: 0.01
    max_shear_y: 0.01
