dataset:
  dataset_name: 'ECG5000'
  in_channels: 1
  data_scaling: True
  batch_sizes:
    stage1: 128
    stage2: 256
  num_workers: 16

exp_params:
  LR: 0.001 #0.01
  weight_decay: 0.001 #0.00001

trainer_params:
  gpus:
    - 0
  max_epochs:
    stage1: 2000
    stage1_ssl: 2000
    stage2: 10000

encoder:
  dim: 64
  dropout_rate: 0.0
  n_resnet_blocks: 4
  downsampled_width: 8

decoder:
  dim: 64
  dropout_rate: 0.0
  n_resnet_blocks: 4

VQVAE:
  n_fft: 8
  codebook:
    size: 32
    dim: 64
  decay: 0.8
  commitment_weight: 1
  emb_dropout: 0.
  perceptual_loss_weight: 0

augmentations:
  time_augs:
    - 'jitter'
    - 'AmpR'
    - 'slope'
    - 'flip'
  time_frequency_augs:
    - 'random_masking'
    - 'block'
    - 'band'
    - 'phase'
    - 'rotation'
    - 'gaussian'
  
  aug_params:
    n_fft: 16
    jitter_std: 0.01
    AmpR_rate: 0.1
    slope_rate: 0.01
    block_size_scale: 0.1
    block_density: 0.1
    num_bands_to_remove: 3
    band_scale_factor: 0.1
    gaus_mean: 0
    gaus_std: 0.01
    rotation_max_angle: 0.1
    min_scale: 0.5
    max_scale: 1.5
    random_mask_density: 0.2


representations:
  test_stage1: False
  test_stage2: False

SSL:
  #method_choice: 'vicreg'
  method_choice: 'barlow_twins'
  weighting: 1

  barlow_twins:
    proj_hid: 4096 #projector hidden layer size
    proj_out: 4096 #projector output layer size
    lambda: 0.005

  vicreg:
    proj_hid: 4096 #projector hidden layer size
    proj_out: 4096 #projector output layer size
    lambda: 25   # sim_loss
    mu: 25       # var_loss
    nu: 1        # cov_loss

MaskGIT:
  choice_temperature: 4 # for masking

  stochastic_sampling: 1  # from (Lee et al., 2022)
  T: 10
  prior_model:
    hidden_dim: 256
    n_layers: 4
    heads: 2
    ff_mult: 1
    use_rmsnorm: True
    p_unconditional: 0.2
  ESS:
    use: False
    error_ratio_ma_rate: 0.3

class_guidance:
  guidance_scale: 1.

